# Desafio 1 — Conectividade básica
# O objetivo deste desafio é testar a conectividade básica entre o Ansible e os hosts definidos no inventário.

# O arquivo hosts.ini é o inventário de hosts do Ansible, onde você define os grupos de hosts e os hosts individuais que serão gerenciados pelo Ansible.
# Um boa prática que eu adotei foi a configuração da conexão ssh feita em .ssh/config, 
# onde eu defino o nome do host, o usuário e a chave de acesso. Assim, no arquivo hosts.ini, eu só preciso referenciar o nome do host definido no arquivo de configuração ssh.
# Mas para deixar explicito, eu também adicionei a variável ansible_host para cada host, apontando para o nome do host definido no arquivo de configuração ssh.

# Forma "simples" de definir o inventário, com as informações passadas de maneira explícita no arquivo hosts.ini.
[webservers]
ubuntu ansible_host=ec2-000.amazonaws.com ansible_user=ubuntu ansible_ssh_private_key_file=~/.ssh/desafiosansible.pem


# Outra forma(que eu uso) é definir apenas o nome do host, e deixar as informações de conexão definidas no arquivo de configuração ssh. 
# Assim, o Ansible irá usar as informações de conexão definidas no arquivo de configuração ssh para se conectar aos hosts.
[dbservers]
suse


# ==========================================================================
# Dentro do arquivo .ssh/config, eu defini os hosts da seguinte maneira:
#
# Host suse
#     HostName ec2-000.amazonaws.com
#     User ec2-user
#     IdentityFile ~/.ssh/ansible-estudos.pem
#
# ==========================================================================



# RODEI E COMANDO USANDO O MODULO PING PARA TESTAR A CONEXÃO COM OS HOSTS DEFINIDOS NO INVENTÁRIO
# ansible all -i inventory/hosts.ini -m ping
# E O RESULTADO FOI O SEGUINTE:
#
# suse | SUCCESS => {
#     "ansible_facts": {
#         "discovered_interpreter_python": "/usr/bin/python3"
#     },
#     "changed": false,
#     "ping": "pong"
# }
# ubuntu | SUCCESS => {
#     "ansible_facts": {
#         "discovered_interpreter_python": "/usr/bin/python3"
#     },
#     "changed": false,
#     "ping": "pong"
# }
