# arquivo de variáveis para o inventário
# este arquivo é usado para definir variáveis específicas para os hosts ou grupos de hosts definidos no arquivo hosts.ini

[ubuntugroup]
ubuntu chave=valor

# Em alguns casos será necessário usar "chave: valor" para definir variáveis com espaços ou caracteres especiais
# Exemplo:
# [ubuntugroup]
# ubuntu chave: "valor com espaços"

# Exemplo:
[linux_servers]
debian01 ansible_host=192.168.0.10 ansible_user=admin ansible_port=22
# Teste: ansible debian01 -m ping

# Outra maneira de definir variáveis é usando um grupo de variáveis para um grupo de hosts
[linux_servers:vars]
ansible_user=admin
ansible_port=22
http_port=8080
variavel=784512 # Podemos criar variaveis unicas

