# Os hosts podem ser separados por servidores.

# [db]
# ubuntu

# variaveis podem ser definidas para cada grupo de hosts, aqui mesmo no arquivo de inventário, ou em arquivos separados.
# [db:vars]
# ansible_python_interpreter=auto_silent
